#! /bin/bash
#
#   Run selftests and check memory

MAIN=zbroker_selftest
VG="valgrind --tool=memcheck --leak-check=full --show-reachable=yes --suppressions=valgrind.supp"

make code
gcc -g -o $MAIN \
    $MAIN.c \
    zpipes_msg.c zpipes_client.c zpipes_server.c \
    -lczmq -lzmq -lzyre -luuid -lsodium
test $? -ne 0 && exit
$VG ./$MAIN
rm -f vgcore.*
