#! /bin/bash
#
#   Run selftests and check memory

VG="valgrind --tool=memcheck --leak-check=full --show-reachable=yes --suppressions=valgrind.supp"
gcc -g -o zpipes_selftest zpipes*.c ${CFLAGS} ${LDFLAGS} -DHAVE_CONFIG_H -lczmq -lzmq -lzyre -luuid -lsodium
$VG ./zpipes_selftest
rm -f vgcore.*
